#!/usr/bin/python3

import argparse
import urllib.request
import urllib.parse
import http.client
import json
import requests

'''
def con_check():
    print("Verifying HTTP connection...")
    conn = http.client.HTTPConnection(args.host, args.port)
    conn.request("GET", "/")
    response = conn.getresponse()
    print("Status Code: {} Reason: {}".format(response.status, response.reason))
'''

def con_check():
    print("Verifying HTTP connection...")
    conn = http.client.HTTPSConnection(args.url)
    conn.request("GET", "/")
    response = conn.getresponse()
    print("Status Code: {} Reason: {}".format(response.status, response.reason))

'''
def list_all():
    urll = urllib.request.Request("https://employee-e829.restdb.io/rest/100-records")
    urll.add_header('content-type', 'application/json')
    urll.add_header('x-apikey', 'a68c55f68a81dd3de249d58bff90f15aa633c')
    urll.add_header('cache-control', 'no-cache')
    content = urllib.request.urlopen(urll).read()
    print(content)
'''

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--host')
    parser.add_argument('--port')
    parser.add_argument('--url')
    args = parser.parse_args()
    con_check()
#    list_all()
    #add()
    #delete()
    #update()