#!/usr/bin/python3

import argparse
#import urllib.request
#import urllib.parse
import http.client
#import json
#import requests

def con_check():
    print("Verifying HTTP connection...")
    conn = http.client.HTTPConnection(args.host, args.port)
    conn.request("GET", "/")
    response = conn.getresponse()
    print("Status Code: {} Reason: {}".format(response.status, response.reason))

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--host')
    parser.add_argument('--port')
    args = parser.parse_args()
    con_check()
    #list_all()
    #add()
    #delete()
    #update()