#!/usr/bin/python3

import http.client
import argparse
import json
import urllib.request
import urllib.parse

default_host = "127.0.0.1"
default_port = "8000"

class efsctl:
    def __init__(self):
        pass

    def efsctl_init():
        pass

    def efsctl_query():
        pass


    def efsctl_execute_controller():
        pass

    def parsers():
        main_parser = argparse.ArgumentParser(prog='efsctl', description='efsctl utility', usage=''' efsctl <controller> <command> [<args>]''')
        main_parser.add_argument('--host', help='Host system to connect')
        main_parser.add_argument('--port', '-p', help='Port of host system to connect')

        


