#!/usr/bin/python3

'''
import http.client  
import sys  
  
conn = http.client.HTTPConnection("127.0.0.1:8000")  
conn.request("GET", "index.html")
response= conn.getresponse()
print(response.status, response.reason)
while response.read(200):
    print(repr(response))
conn.close()  
'''

import urllib.request
import urllib.parse

with urllib.request.urlopen('http://127.0.0.1:8000/index.html') as f:
    f.read().decode()