#!/usr/bin/env python3

import socket

HOST = '127.0.0.1' 
PORT = 65432       

while True:
    msg = (input('Enter message:'))
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((HOST, PORT))
        s.sendall(msg.encode())
        data = s.recv(1024).decode()
    print('Received', repr(data))
